FROM python:3

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

RUN python -m pip install -r requirements.txt

COPY ./ /app

EXPOSE 8501

CMD python -m streamlit run app.py --server.port=8501 --server.address=0.0.0.0